# Generated by Django 4.0.4 on 2022-05-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('address_line_one', models.CharField(max_length=200)),
                ('address_line_two', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('paid_to_date', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
