# Generated by Django 4.0.4 on 2022-05-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Client',
        ),
    ]
