# Generated by Django 4.0.4 on 2022-05-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
